### ISSUE TITLE
New link submission: Example Title

### ISSUE THREAD

**Issue by jessicaschilling** [jessicaschilling/ipfs-gui-mental-model#11]
### To do:
- [ ] Add the datum in the code block below to the ["Tutorial" JSON source](https://github.com/ipfs/ipfs-blog/edit/main/src/_blog/tutorials.md) 
- [ ] If the code block specifies a value for `card_image`, [grab the submitted art](https://dl.airtable.com/.attachments/224bdc56e649029d204afdeb3d45674f/fdfb347e/ipfs-logo.png) and upload it to the [`public` directory](https://github.com/ipfs/ipfs-blog/tree/main/src/.vuepress/public)
- [ ] If there's more than one tag in the code block, break those out into one per line (clearly this isn't seamless yet)

```
  - title: Example Title
    path: www.foo.bar
    card_image: ipfs-logo.png
    date: 2021-03-23
    tags:
      - CID,Censorship,CDN,case study
```

_Submitted on: 2021-03-03T00:40:41.000Z_
_Submitter's GitHub handle, if provided: @jessicaschilling_
_This issue was automatically generated after receiving a new response to the [IPFS Blog & News submissions](https://airtable.com/shrNH8YWole1xc70I) form._
