### ISSUE TITLE
New link submission: asdfasdf

### ISSUE THREAD

**Issue by jessicaschilling** [jessicaschilling/ipfs-gui-mental-model#7]
A new link submission was added via the form at https://airtable.com/shrNH8YWole1xc70I 🎉
Please PR the following JSON to the top of the data at https://github.com/ipfs/ipfs-blog/blob/main/src/_blog/events.md ...

```
  - title: asdfasdf
    path: sdfsdf
    card_image: '/2021-02-23-event-meetup.png'
    date: 2021-03-03
    tags:
      - whitepaper
```
If the person who submitted the issue provided a GitHub handle, we'll name-check them after the colon:
This issue is automatically generated by Airtable + Zapier. Bleep bloop!
