### ISSUE TITLE
New link submission: Example Title

### ISSUE THREAD

**Issue by jessicaschilling** [jessicaschilling/ipfs-gui-mental-model#9]
### 🎉  Someone submitted a new link using the [IPFS Blog & News submissions form](https://airtable.com/shrNH8YWole1xc70I)!

Submitted on: 2021-03-03T00:40:41.000Z
Submitter's GitHub handle, if provided: @jessicaschilling

Please [edit the JSON source](https://github.com/ipfs/ipfs-blog/edit/main/src/_blog/tutorials.md) to add the following datum.

**Important!** If a `card_image` value is specified below, you also need to [grab the submitted art](https://dl.airtable.com/.attachmentThumbnails/722bf1bbe2b9f89a154728d512e4aca9/6b22cc62) and upload it to the [`public` directory](https://github.com/ipfs/ipfs-blog/tree/main/src/.vuepress/public).

```
  - title: Example Title
    path: www.foo.bar
    card_image: '/ipfs-logo.png'
    date: 2021-03-23
    tags:
      - CID,Censorship,CDN,case study
```

Also, if there's more than one tag, break those out into one per line. Clearly this isn't seamless yet.

_This issue was automatically generated by Airtable + Zapier. Bleep bloop!_
